### ISSUE TITLE
Remove send on closed channel

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#1020]
In the devnet, the following error was observed after some of the nodes panicked:

```
panic: send on closed channel

goroutine 128 [running]:
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.sendError(0xc0023f9140, 0x108c640, 0xc01fa7b310)
        /work/pkg/p2p/peer/peer.go:211 +0x49
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*Writer).writeLoop(0xc002231110, 0x10a2c40, 0xc00245ac00, 0xc0023f9080, 0xc0023f9140)
        /work/pkg/p2p/peer/peer.go:295 +0x650
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*Writer).Serve(0xc002231110, 0x10a2c40, 0xc00245ac00, 0xc0023f9080, 0xc0023f9140)
        /work/pkg/p2p/peer/peer.go:225 +0xd8
created by github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.Create
        /work/pkg/p2p/peer/peer.go:202 +0x106
```

This is accompanied by the logs showing that some connections are dropped:

```
{"error":"write tcp 159.89.24.209:58020-\u003e165.227.33.253:7100: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:47Z"}
{"coordinator_round":45145,"level":"debug","msg":"storing future round for later","process":"agreement","round":45147,"time":"2021-04-16T14:29:53Z","topic":"Agreement"}
{"error":"write tcp 159.89.24.209:60666-\u003e104.131.173.173:7100: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:54Z"}
{"error":"write tcp 159.89.24.209:7100-\u003e143.110.156.197:55554: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:55Z"}
{"coordinator_round":45145,"level":"debug","msg":"storing future round for later","process":"agreement","round":45148,"time":"2021-04-16T14:30:11Z","topic":"Agreement"}
{"coordinator_round":45145,"level":"debug","msg":"storing future round for later","process":"agreement","round":45146,"time":"2021-04-16T14:30:11Z","topic":"Agreement"}
{"error":"read tcp 159.89.24.209:38204-\u003e46.101.134.69:7100: i/o timeout","level":"warning","msg":"error reading message","process":"peer","time":"2021-04-16T14:29:58Z"}
{"error":"read tcp 159.89.24.209:38204-\u003e46.101.134.69:7100: i/o timeout","level":"warning","msg":"error received from peer","process":"server","time":"2021-04-16T14:30:11Z"}
{"error":"write tcp 159.89.24.209:7100-\u003e134.122.34.54:50876: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:58Z"}
{"error":"write tcp 159.89.24.209:55820-\u003e165.227.237.8:7100: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:58Z"}
{"error":"write tcp 159.89.24.209:38204-\u003e46.101.134.69:7100: write: broken pipe","level":"warning","msg":"error writing message","process":"writeloop","time":"2021-04-16T14:29:58Z"}
```

Right after these entries, the logs indicate a new startup.

**Comment by julesdesmit** [comment]
The nodes it was connected to seem to time out about 5 blocks later, which is about 30 seconds or so. The problem is definitely with `159.89.24.209`, so it may be good to find the cause of this random broken pipe.
