### ISSUE TITLE
Ensure a proper cleanup of all resources in the node in case of a panic or kill signal

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#1029]
On the devnet, for instance, we observe that restarting a node after a crash does not work, since the control of the UNIX domain socket file descriptor was never relinquished. This, and many other things, need to be taken care of.

**Comment by pmoranga** [comment]
After some research it was identified that the processes shutdown properly only when receiving "Interrupt" signal (SIGINT).

When received SIGTERM and SIGQUIT, shutdown is not made properly.

**Comment by autholykos** [comment]
In `cmd/dusk/action.go` signal trapping is left to the following line:

```
signal.Notify(interrupt, os.Interrupt)
```
 `os.Interrupt` is restricted solely to the most portable OS signals such as `SIGINT` and `SIGKILL`. In order to trap `SIGTERM` and `SIGQUIT` this should be changed into 

```
signal.Notify(interrupt, os.Interrupt, os.SIGTERM, os.SIGQUIT)
``` 

Potentially, we might wanna handle the latter two differently by producing a core dump (and eventually avoid cleaning up temp-files and other debug related info)

**Comment by julesdesmit** [comment]
This issue was filed mostly to deal with this panic which repeats itself after a crash on devnet:
```
panic: (*logrus.Entry) 0xc000035570

goroutine 62 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000148a10, 0xc0001a7e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0001a8d20, 0x0, 0xc0007a7758, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Panic(0xc0001a8d20, 0xc0007a7758, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:325 +0x55
main.Setup.func2(0xc0001a36c0)
        /work/cmd/dusk/server.go:287 +0x16a
created by main.Setup
        /work/cmd/dusk/server.go:282 +0x11f0
```

It seems that the node can not set the local grpc server back up
