### ISSUE TITLE
Panic observed at point of peermsg.(*Inv).Decode on invalid wire messages

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#228]
```
panic: runtime error: makeslice: len out of range

goroutine 7366152 [running]:
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer/peermsg.(*Inv).Decode(0xc00084b9b0, 0xc0018ef500, 0xc7cf763b4989c309, 0x0)
        /root/go/pkg/mod/github.com/dusk-network/dusk-blockchain@v0.2.1-0.20191229115357-479399269943/pkg/p2p/peer/peermsg/inventory.go:63 +0x64
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer/responding.(*DataBroker).SendItems(0xc001702400, 0xc0018ef500, 0x90faa5, 0xc00084ba80)
        /root/go/pkg/mod/github.com/dusk-network/dusk-blockchain@v0.2.1-0.20191229115357-479399269943/pkg/p2p/peer/responding/databroker.go:38 +0x6f
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*messageRouter).route(0xc0007e8ba0, 0xc0018ef506, 0xc0018ef500)
        /root/go/pkg/mod/github.com/dusk-network/dusk-blockchain@v0.2.1-0.20191229115357-479399269943/pkg/p2p/peer/router.go:63 +0x499
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*messageRouter).Collect(0xc0007e8ba0, 0xc0018ef500, 0x4, 0x47b7d1d2e2646101)
        /root/go/pkg/mod/github.com/dusk-network/dusk-blockchain@v0.2.1-0.20191229115357-479399269943/pkg/p2p/peer/router.go:39 +0x7b
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*Reader).ReadLoop(0xc001702420)
        /root/go/pkg/mod/github.com/dusk-network/dusk-blockchain@v0.2.1-0.20191229115357-479399269943/pkg/p2p/peer/peer.go:249 +0xda
created by github.com/dusk-network/dusk-explorer/node.(*Node).OnAccept
        /root/dusk-explorer/node/node.go:170 +0x4f7

```

**Comment by julesdesmit** [comment]
The way this looks, it may have been an out of memory error, though it's hard to say with only this part of the panic. Either way, I think a patch for this will be simple enough.
