### ISSUE TITLE
Update NewCallbackListener for NewSafeCallbackListener in order to avoid race conditions on listeners

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#607]

**Comment by devtomnl** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa20579]

goroutine 183694 [running]:
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.MarshalStepVotes(0xc00108f8d8, 0xc00108fb10, 0xc0016b9c08, 0x7)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/agreement.go:405 +0x29
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.StepVotesMsg.Copy(0xc0002f6090, 0x81, 0x81, 0x90e, 0x6, 0x179f560, 0x20, 0x20, 0x0, 0x0, ...)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/agreement.go:116 +0x63
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.Clone(0x10ba100, 0xc0013a14c0, 0xc0002a9701, 0xc0016b9dda)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/message.go:79 +0xe0
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*CallbackListener).Notify(0xc000248410, 0x10ba100, 0xc0013a14c0, 0x1, 0xc000f8a801)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/listener.go:35 +0x44
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*multiListener).Forward(0xc000232b40, 0xd9ab20, 0x10ba100, 0xc0013a14c0)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/listener.go:180 +0x13c
created by github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*EventBus).Publish
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/publisher.go:35 +0x81
```
