### ISSUE TITLE
MarshalStepVotes panic when trying to marhsal invalid vote

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#611]
stacktrace:

```
time="2020-08-04T22:59:24+02:00" level=info msg="initializing node..." app=dusk prefix=main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa18649]

goroutine 15778 [running]:
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.MarshalStepVotes(0xc0001798d8, 0xc000179b10, 0xc976aa, 0xd63980)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/agreement.go:405 +0x29
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.StepVotesMsg.Copy(0xc0002ec240, 0x81, 0x81, 0xc2, 0x6, 0x1753de0, 0x20, 0x20, 0x0, 0x0, ...)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/agreement.go:116 +0x63
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.Clone(0x1088dc0, 0xc0015d90c0, 0xc0012bd501, 0xc000d6fa3a)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/message.go:79 +0xe0
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*CallbackListener).Notify(0xc000198430, 0x1088dc0, 0xc0015d90c0, 0x1, 0xc000df8001)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/listener.go:35 +0x44
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*multiListener).Forward(0xc000227cc0, 0xd74920, 0x1088dc0, 0xc0015d90c0)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/listener.go:180 +0x13c
created by github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*EventBus).Publish
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/publisher.go:25 +0x81
```

**Comment by autholykos** [comment]
Closed via #608
