### ISSUE TITLE
panic on pkg/p2p/wire/message.Clone kills node

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#637]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa1c2f6]

goroutine 13 [running]:
github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message.Clone(0x1097fa0, 0xc001248e80, 0xc00038a240, 0xc001248ea0)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/message/message.go:79 +0xd6
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*CallbackListener).Notify(0xc000292290, 0x1097fa0, 0xc001248e80, 0x1, 0x1)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/listener.go:35 +0x44
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*EventBus).Publish(0xc0002c53d0, 0x24, 0x1097fa0, 0xc001248e80, 0xc001248e80, 0xc0002e6f10, 0xb92679)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus/publisher.go:33 +0x128
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).beginAccepting(0xc0001b0100, 0xc001248e40, 0xc001248e40)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/core/chain/chain.go:264 +0x21f
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).onAcceptBlock(0xc0001b0100, 0x1097fa0, 0xc001248d40, 0x0, 0x1)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/core/chain/chain.go:276 +0xce
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).Listen(0xc0001b0100)
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/pkg/core/chain/chain.go:220 +0xa6e
created by main.LaunchChain
	/opt/gocode/src/github.com/dusk-network/dusk-blockchain/cmd/dusk/server.go:80 +0x286

```

**Comment by autholykos** [comment]
Seems like the problems pertains to the propagation of a `nil` message when stopping the consensus. The fix should probably be to define an `EMPTY` message and use that instead. See https://github.com/dusk-network/dusk-blockchain/blob/f95e3ce3a5f26e8c6ff81118deefd43e5c41a4a3/pkg/core/chain/chain.go#L264
